<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet type="text/xsl" href="htmlplot.xsl"?>

<!DOCTYPE plotscript [
	<!ELEMENT plotscript (section+)>
	<!ATTLIST plotscript lastmodified CDATA "the dawn of time">
	<!ATTLIST plotscript show-alias CDATA "yes">
	<!ELEMENT section (description?,command*)>
	<!ATTLIST section title CDATA #REQUIRED>
	<!ELEMENT command ((cannon,shortname,description,example*,seealso?) |
					   (alias,shortname))>
	<!ATTLIST command id ID #REQUIRED
			          created CDATA #IMPLIED>
  	<!ELEMENT cannon      (#PCDATA)>
  	<!ELEMENT shortname   (#PCDATA)>
  	<!ELEMENT description ANY>
  	<!ELEMENT example     (#PCDATA)>
  	<!ATTLIST example c IDREF #IMPLIED>
  	<!ELEMENT alias       (#PCDATA)>
  	<!ELEMENT seealso (ref+)>

  	<!ELEMENT ref         (#PCDATA)>
  	<!ELEMENT lb		  (#PCDATA)>
  	<!ELEMENT param		  (#PCDATA)>
]>
<!--

DOCUMENTATION FOR THIS XML FILE:

This markup (hereby refered to as PDL (Plotscript Dictionary Language)) is
designed to reduce the time spent maintaining the Plotscripting Dictionary, and
to enable easier porting to other formats.

The root element is the <plotscript> element. It has a lastmodified attribute,
which is the text date that the file was last modified. Update this when you
make a change.

In <plotscript>, there is a series of <section> elements, each with a title
attribute. These are to group the plotscripting commands into logical groups,
such as <section title="Wait Commands"> or <section title="Math Operators">

The heart of the PDL are the <command> elements inside the <section>s. It has a
single attribute, id. This is essentially the whitespace stripped version of the
command (the "wait for text box" command would have an id of "waitfortextbox").
This is used to uniquely identify each command. It's used in many ways, from
crosslinking command entries to generating a file for HssEd to use.

Inside the <command> element are either two or four+ elements, in this order:
Case 1: Full command definition
  <cannon> - This is the "cannonical" form of the command: the fully spaced
  			 command with parameter prototypes. Example: move hero to x (who, x)
  <shortname> - This is the short version of the command, used for crosslinking,
  				indexes, etc. It is the <cannon> element, minus the parameters.
  				Example: move hero to x
  <description> - This is a paragraph (or more) of text describing what the
  				  command does, and how to use it. Use <lb/> to put paragraphs
  				  in, and <p></p> when refering to a parameter (to avoid user
  				  confusion) No HTML is allowed (at this time) Example: Well, it
  				  would be pretty long...
  <example>* - Finally, most commands should have some sort of example on how to
  			   use the command. It will be displayed in a mono-space font, so
  			   it's easy to Plotscript. But, be sure to format it properly:
			   Example:
			   <example># first example line has no line-break
# the second (and more) lines should have no indentation
# and so forth</example>

Case 2: Alias command definition
  <alias> - If a command is an alias to another command (or is so closely
  			related that they're in the same entry, use the <alias> element. Put
  			the ID of the real command in here. Example: begin
  <shortname> - Aliases also need a short name, since they are technically
  				different from their alias. Example: end

Basically, you should be able to examine the entries that already exist. It's
fairly self evident what everything does.

These are cut-and-paste copies of <command> elements, so you don't have to type
everything out 10000000000 times. They are also indented properly for this file.

#===== Full description

		<command id="">
			<cannon></cannon>
			<shortname></shortname>
			<description></description>
			<example></example>
		</command>

#===== Full description with borrowed example

		<command id="">
			<cannon></cannon>
			<shortname></shortname>
			<description></description>
			<example c="">
		</command>

#===== Alias

		<command id="">
			<alias></alias>
			<shortname></shortname>
		</command>


#=====

Which reminds me: Indentation. For each "level" you go down in the heirarchy,
you indent once. Many code specific editors will maintain this indentation level
for until you explicitly change it, so it isn't difficult. Notepad users will
have to do it manually, but you MUST do it. Remember: 1 indent = 1 tab.

"Mono means 'one'. Rail means 'rail'. And that concludes our training."
	~ Monorail guy, Simpsons

-->
<plotscript lastmodified="August 03, 2006 hasta-la-qb version">
	<section title="Declarations">
		<command id="definescript">
			<cannon>define script (id,name,arguments)</cannon>
			<shortname>define script</shortname>
			<description>The define script command names a script, and associates it with an ID number. Every script must have a unique ID number for your game to call it directly (scripts that will only be called indirectly, by other scripts can use the special ID autonumber). The first argument is the <p>ID number</p>. It is a number between 1 and 16383. If you try to give two individual scripts the same <p>ID number</p>, your script file will not compile. The next argument is the <p>name</p> of the script. this is the same name that will used later in your script command. The third argument is the number of arguments that the script can accept. If it doesnt need any arguments (most scripts dont) then use <ref>none</ref>. If there are arguments, you then follow the argument count with default values for each argument.</description>
			<example># example of a simple script definition
define script (1,my first script,none)</example>
			<example># example of a script definition with arguments. this script
# has three arguments, all of which default to zero if they
# are not specified
define script (2,my fancy script,3,0,0,0)</example>
		</command>
		<command id="script">
			<cannon>script, name, argumentnames (statements)</cannon>
			<shortname>script</shortname>
			<description>The script command contains the actual source code of a plotscript. every script command must have a corresponding <ref>definescript</ref> statement. Script starts with the keyword script, a comma, and then the name of the script. If there are any arguments to the script, you list their names separated by commas after the name of the script. Then comes the text of the script. It is usually enclosed in <ref>begin</ref> and <ref>end</ref> statements.</description>
			<example># example of a simple script
script,my first script,begin
	# commands go here
end</example>
			<example># example of a script with arguments
script,my fancy script,fe,fi,fo,begin
	# commands go here,
	# and they can use the aruments fe, fi, and fo
	# that where passed to the script
end</example>
		</command>
		<command id="globalvariable">
			<cannon>global variable (id,name)</cannon>
			<shortname>global variable</shortname>
			<description>Creates a global variable that can be used in any script. The first argument to the global variable declaration is a unique ID number. The second argument is the name of the variable. The ID number for a global variable is a number from 0 to 1024. Each global variable must have a unique number, but this number will not conflict with the ID numbers you use for scripts. It is all right to have a script and a global variable with the same ID number. See also <ref>variable</ref></description>
			<example># any script can read and set the value of a global
global variable(1,mini game score)</example>
		</command>
		<command id="variable">
			<cannon>variable (name)</cannon>
			<shortname>variable</shortname>
			<description>Creates a local variable that can only be used inside the script where it was created. The value of this variable is lost when the script ends. If you need a variable who&apos;s value persists between calls to a script, or that is automatically saved when the player saves their game, you will need to use a <ref>globalvariable</ref> instead.</description>
			<example>variable(points) # make a new variable
variable+=1 # add one to it</example>
		</command>
		<command id="defineconstant">
			<cannon>define constant (number,name)</cannon>
			<shortname>define constant</shortname>
			<description>Creates a global constant. The first argument is the number that the constant will represent, and the second argument is the name of the constant. Use constants to replace commonly used numbers with friendly names. The following constants have been delacred for you in PLOTSRC.HSD:<lb /><ref>zero</ref> <ref>one</ref> <ref>two</ref> <ref>three</ref> <ref>four</ref> <ref>five</ref> <ref>six</ref> <ref>seven</ref> <ref>eight</ref> <ref>nine</ref> <ref>ten</ref> <ref>false</ref> <ref>true</ref> <ref>off</ref> <ref>on</ref> <ref>north</ref> <ref>east</ref> <ref>south</ref> <ref>west</ref> <ref>up</ref> <ref>down</ref> <ref>left</ref> <ref>right</ref> <ref>upkey</ref> <ref>downkey</ref> <ref>leftkey</ref> <ref>rightkey</ref> <ref>usekey</ref> <ref>cancelkey</ref> <ref>menukey</ref> <ref>anykey</ref> <ref>me</ref> <ref>none</ref> <ref>autonumber</ref> <ref>currentstat</ref> <ref>maximumstat</ref> <ref>northwall</ref> <ref>eastwall</ref> <ref>southwall</ref> <ref>westwall</ref> <ref>vehiclea</ref> <ref>vehiclea</ref> <ref>harmtile</ref> <ref>overheadtile</ref></description>
		</command>
		<command id="include">
			<cannon>include, filename</cannon>
			<shortname>include</shortname>
			<description>The include command inserts another text file into your script. It is followed by a single filename that tells what file will be included. Windows long filenames are not supported. Every plotscript file should start with include, plotscr.hsd The PLOTSCR.HSD file contains definitions and constants for most of the other plotscripting commands.</description>
			<example>include, plotscr.hsd # Plotscripting definitions
include, mygame.hsi # constants particular to my game</example>
		</command>
	</section>
	<section title="Wait Commands">
		<command id="wait">
			<cannon>wait (ticks)</cannon>
			<shortname>wait</shortname>
			<description>Makes the script wait for the specified number of ticks. There are roughly 18 ticks to a second, but this can vary under some conditions. If you leave out the argument, it will wait for one tick.</description>
			<example>show text box(2) # Show a text box
wait(50) # Wait about 3 seconds
advance text box # "hit spacebar"</example>
		</command>
		<command id="waitfortextbox">
			<cannon>wait for text box</cannon>
			<shortname>wait for text box</shortname>
			<description>Makes the script wait until there is no text box displaying on the screen. Useful to know when to move on after using a <ref>showtextbox</ref> command</description>
			<example>show text box(2) # Show a text box
wait for text box # wait until the player continues</example>
		</command>
		<command id="waitforhero">
			<cannon>wait for hero (who)</cannon>
			<shortname>wait for hero</shortname>
			<description>Waits for the specified hero stop walking. Use the constant <ref>me</ref> to refer to the leader, or use numbers 0,1,2,3 to refer to a specific hero. If you leave out the argument, the first hero will be assumed.</description>
			<example>move hero to y (me, 10) # move hero to (x, 10)
wait for hero (me) # wait until he stops</example>
		</command>
		<command id="waitforkey">
			<cannon>wait for key (key)</cannon>
			<shortname>wait for key</shortname>
			<description>Waits for the player to press a key. You can use the follwing constants: <ref>anykey</ref>, <ref>upkey</ref>, <ref>downkey</ref>, <ref>leftkey</ref>, <ref>rightkey</ref>, <ref>usekey</ref>, <ref>cancelkey</ref>, or <ref>menukey</ref>. If you do not specify, then <ref>anykey</ref> will be used.</description>
			<example>show text box(623) # "press cancel!"
wait for key(cancel key)</example>
		</command>
		<command id="waitfornpc">
			<cannon>wait for NPC (who)</cannon>
			<shortname>wait for NPC</shortname>
			<description>Waits for the specified NPC to stop walking. The argument is the number of the NPC, 0 to 35. If more than one copy of the NPC exists on the map, it only checks the first one.</description>
			<example>walk NPC (2,up,3) # make the NPC go up three spaces
wait for NPC (2) # wait until he&apos;s done</example>
		</command>
		<command id="waitforcamera">
			<cannon>wait for camera</cannon>
			<shortname>wait for camera</shortname>
			<description>Wait for the camera to stop panning after a <ref>pancamera</ref> or <ref>focuscamera</ref> command.</description>
			<example>pan camera (left,10) # show the villan 10 tiles off screen
wait for camera # wait until he&apos;s on screen</example>
		</command>
		<command id="waitforall">
			<cannon>wait for all</cannon>
			<shortname>wait for all</shortname>
			<description>Waits for any camera motion to stop, waits for all heros to stop walking, and if <ref>suspendnpcs</ref> is active, waits for all NPCs to stop walking.</description>
			<example># do a bunch of things all at once
wait for all # wait until everything is done</example>
		</command>
	</section>
	<section title="Suspend and Resume">
		<command id="suspendplayer">
			<cannon>suspend player</cannon>
			<shortname>suspend player</shortname>
			<description>Blocks the player from controlling the game, so the plotscript can have exclusive control. The one exception to this is text boxes. The player can advance text boxes no matter what, unless you use <ref>suspendboxadvance</ref>.</description>
			<example>suspend player
# do stuff
resume player</example>
		</command>
		<command id="resumeplayer">
			<cannon>resume player</cannon>
			<shortname>resume player</shortname>
			<description>Restores normal control after a <ref>suspendplayer</ref> command. This is very important. If you use <ref>suspendplayer</ref>, but forget resume player, the game will be stuck after the script ends.</description>
			<example c="suspendplayer" />
		</command>
		<command id="suspendnpcs">
			<cannon>suspend NPCs</cannon>
			<shortname>suspend NPCs</shortname>
			<description>Stops NPCs from walking around automatically. When suspend NPCs is run, all NPCs stop in their tracks, ready for you to control them with the <ref>walknpc</ref> command</description>
			<example>suspend NPCs
# do stuff
resume NPCs</example>
		</command>
		<command id="resumenpcs">
			<cannon>resume NPCs</cannon>
			<shortname>resume NPCs</shortname>
			<description>Restores automatic NPC movement after a <ref>suspendnpcs</ref> command</description>
			<example c="suspendnpcs" />
		</command>
		<command id="suspendobstruction">
			<cannon>suspend obstruction</cannon>
			<shortname>suspend obstruction</shortname>
			<description>Allows heros to walk through NPCs, allows NPCs to walk through heros, and allows NPCs to walk through each other. Use <ref>resumeobstruction</ref> to restore normal obstruction behavior.</description>
			<example>suspend obstruction
# walk through things
resume obstruction</example>
		</command>
		<command id="resumeobstruction">
			<cannon>resume obstruction</cannon>
			<shortname>resume obstruction</shortname>
			<description>Restores normal obstruction after a <ref>suspendobstruction</ref> command</description>
			<example c="suspendobstruction" />
		</command>
		<command id="suspendherowalls">
			<cannon>suspend hero walls</cannon>
			<shortname>suspend hero walls</shortname>
			<description>Allows heros to walk through walls. Use <ref>resumeherowalls</ref> to restore normal wall behavior.</description>
			<example>suspend hero walls # hero is now a ghost
# walk through things
resume hero walls # back to mortality...</example>
		</command>
		<command id="resumeherowalls">
			<cannon>resume hero walls</cannon>
			<shortname>resume hero walls</shortname>
			<description>Restores normal wall behavior after a <ref>suspendherowalls</ref> command</description>
			<example c="suspendherowalls" />
		</command>
		<command id="suspendnpcwalls">
			<cannon>suspend NPC walls</cannon>
			<shortname>suspend NPC walls</shortname>
			<description>Allows NPCs to walk through walls. Use <ref>resumenpcwalls</ref> to restore normal wall behavior.</description>
			<example>suspend NPC walls # npc is now a ghost
# walk through things
resume NPC walls # back to mortality...</example>
		</command>
		<command id="resumenpcwalls">
			<cannon>resume NPC walls</cannon>
			<shortname>resume NPC walls</shortname>
			<description>Restores normal wall behavior after a <ref>suspendnpcwalls</ref> command.</description>
			<example c="suspendnpcwalls" />
		</command>
		<command id="suspendcaterpillar">
			<cannon>suspend caterpillar</cannon>
			<shortname>suspend caterpillar</shortname>
			<description>Stops your other heros from following the leader. This is useful when you want to control them individually with <ref>walkhero</ref> commands. In earlier versions this was misspelled as suspend catapillar. The old spelling still works for backwards compatability.</description>
			<example>suspend caterpillar # cutscene
# move heros, probably fight a battle or two...
resume caterpillar # normal game again.</example>
		</command>
		<command id="resumecaterpillar">
			<cannon>resume caterpillar</cannon>
			<shortname>resume caterpillar</shortname>
			<description>Reverses the <ref>suspendcaterpillar</ref> command, and makes your other heros follow the leader as normal. In earlier versions this was misspelled as resume catapillar. The old spelling still works for backwards compatability.</description>
			<example c="suspendcaterpillar" />
		</command>
		<command id="suspendcatapillar">
			<alias>suspendcaterpillar</alias>
			<shortname>suspend catapillar</shortname>
		</command>
		<command id="resumecatapillar">
			<alias>resumecaterpillar</alias>
			<shortname>resume catapillar</shortname>
		</command>
		<command id="suspendrandomenemies">
			<cannon>suspend random enemies</cannon>
			<shortname>suspend random enemies</shortname>
			<description>Prevents enemies from attacking your party while walking over tiles that can normally spawn random battles. This is useful to prevent battles from interrupting a plotscript. In earlier versions, this was misspelled as suspend random enemys. The old spelling still works for backwards compatability.</description>
			<example>suspend random enemies # no battles for now
walk hero (me, up, 10) # cross pit of evil monsters of doom
resume random enemies # back to normal</example>
		</command>
		<command id="resumerandomenemies">
			<cannon>resume random enemies</cannon>
			<shortname>resume random enemies</shortname>
			<description>Undoes the <ref>suspendrandomenemies</ref> command and allows random battles to occur as normal. In earlier versions, this was misspelled as resume random enemys. The old spelling still works for backwards compatability.</description>
			<example c="suspendrandomenemies" />
		</command>
		<command id="suspendrandomenemys">
			<alias>suspendrandomenemies</alias>
			<shortname>suspend random enemys</shortname>
		</command>
		<command id="resumerandomenemys">
			<alias>resumerandomenemies</alias>
			<shortname>resume random enemys</shortname>
		</command>
		<command id="suspendboxadvance">
			<cannon>suspend box advance</cannon>
			<shortname>suspend box advance</shortname>
			<description>Prevents the player from advancing or clearing text boxes by pressing keys. While this is active, the only way to make a text box advance is with the <ref>advancetextbox</ref> command. Be very careful with this command, since you do not want to leave the player stuck on a text box forever.</description>
			<example>suspend box advance # stop players from mucking things up
show text box(2) # Show a text box
wait(45) # Wait about 3 seconds
advance text box # "hit spacebar"
resume box advance # go back to normal</example>
		</command>
		<command id="resumeboxadvance">
			<cannon>resume box advance</cannon>
			<shortname>resume box advance</shortname>
			<description>Undoes the <ref>suspendboxadvance</ref> command and allows the player to advance and clear text boxes by pressing keys as normal.</description>
			<example c="suspendboxadvance" />
		</command>
		<command id="suspendoverlay">
			<cannon>suspend overlay</cannon>
			<shortname>suspend overlay</shortname>
			<description>Prevents overhead tiles from being drawn over heros and NPCs.</description>
		</command>
		<command id="resumeoverlay">
			<cannon>resume overlay</cannon>
			<shortname>resume overlay</shortname>
			<description>Causes overhead tiles to be drawn over heros and NPCs as normal.</description>
		</command>
		<command id="suspendmapmusic">
			<cannon>suspend map music</cannon>
			<shortname>resume map music</shortname>
			<description>Causes ambient music not to automatically play when you enter a map. Does not affect the currently playing music, or the map's ambient music. Use when playing thematic music during a scene that involves changing maps.</description>
			<example># begin scene
play song(song:Happy Times)
show textbox (117)
wait for textbox
# goto another map without triggering music
fade screen out
wait
suspend map music
use door(3)
fade screen in
# continue scene
show textbox (118)
wait for textbox
# return to normal music behaviour and play the ambient music
resume map music
play song (get ambient music)</example>
		<seealso><ref>setambientmusic</ref> <ref>getambientmusic</ref></seealso>
		</command>
		<command id="resumemapmusic">
			<cannon>resume map music</cannon>
			<shortname>resume map music</shortname>
			<description>Causes ambient music to automatically start playing when you enter a map again after a <ref>suspendmapmusic</ref> command.</description>
		</command>
	</section>
	<section title="Moving Heros">
		<command id="walkhero">
			<cannon>walk hero (who, direction, distance)</cannon>
			<shortname>walk hero</shortname>
			<description>Makes the specified hero move in the specified direction for the specified number of tiles. The first argument tells who to move. Use <ref>me</ref> or numbers 0-3. The second argument is the direction. Use the constants: <ref>north</ref>, <ref>south</ref>, <ref>east</ref>, <ref>west</ref>, <ref>up</ref>, <ref>down</ref>, <ref>left</ref>, or <ref>right</ref>. The third argument is the number of tiles to move. If you leave out the third argument, the hero will move one tile. Walk hero is usually used with the <ref>waitforhero</ref> command. You should normally use the <ref>suspendplayer</ref> command before moving heros, and if you want to move heros other than the leader, you should use the <ref>suspendcaterpillar</ref> command.</description>
			<example>suspend player # stop player
walk hero(me,up,3) # move him up 3 tiles
resume player # ok, done</example>
		</command>
		<command id="setherodirection">
			<cannon>set hero direction(who, direction)</cannon>
			<shortname>set hero direction</shortname>
			<description>Makes the specified hero face in the specified direction. The following constants are avaialable for direction: <ref>north</ref>, <ref>south</ref>, <ref>east</ref>, <ref>west</ref>, <ref>up</ref>, <ref>down</ref>, <ref>left</ref>, or <ref>right</ref>.</description>
			<example>set hero direction(me,right) # face right</example>
		</command>
		<command id="setheroframe">
			<cannon>set hero frame(who, frame)</cannon>
			<shortname>set hero frame</shortname>
			<description>Sets the walking frame of the specified hero to 0 or 1.</description>
		</command>
		<command id="setheroposition">
			<cannon>set hero position (who, x, y)</cannon>
			<shortname>set hero position</shortname>
			<description>Instantly moves the specified hero to an X,Y position on the map. The coordinates are in units of tiles. For pixel-positioning use the <ref>puthero</ref> command.</description>
		</command>
		<command id="setheroz">
			<cannon>set hero z (who, z)</cannon>
			<shortname>set hero z</shortname>
			<description>Sets the Z location of the specified hero. The Z location is the number of pixels above the tile they are standing on. Useful for scripts where you want a hero to jump or levitate.</description>
		</command>
		<command id="walkherotox">
			<cannon>walk hero to x (who,x)</cannon>
			<shortname>walk hero to x</shortname>
			<description>Makes the specified hero walk to a given X coordinate on the map</description>
		</command>
		<command id="walkherotoy">
			<cannon>walk hero to y (who,x)</cannon>
			<shortname>walk hero to y</shortname>
			<description>Makes the specified hero walk to a given Y coordinate on the map</description>
		</command>
		<command id="setherospeed">
			<cannon>set hero speed (who, speed)</cannon>
			<shortname>set hero speed</shortname>
			<description>Changes the walking speed of the specified hero. If you do not specify a speed, the hero&apos;s speed will return to the default, 4. Be careful with using speeds that do not divide evenly into 20, because tiles are 20 pixels in size, and an irregular walking speed may cause your hero to become misaligned with the tiles.</description>
		</command>
		<command id="usedoor">
			<cannon>use door (number)</cannon>
			<shortname>use door</shortname>
			<description>Instantly uses the numbered door, just as if you had stepped into it.</description>
		</command>
		<command id="teleporttomap">
			<cannon>teleport to map (map, x, y)</cannon>
			<shortname>teleport to map</shortname>
			<description>An alternative to <ref>usedoor</ref>, teleport to map moves you to a given x,y position on the specified map without the need to create a door-link on the map. Teleport to map does not fade to black.</description>
		</command>
		<command id="dismountvehicle">
			<cannon>dismount vehicle</cannon>
			<shortname>dismount vehicle</shortname>
			<description>Makes you dismount whatever vehicle you are riding. If you are not riding a vehicle, nothing will happen.</description>
		</command>
		<command id="heroiswalking">
			<cannon>hero is walking (who)</cannon>
			<shortname>hero is walking</shortname>
			<description>Returns <ref>true</ref> if the specified hero (by position in the caterpillar) is currently walking. Returns <ref>false</ref> if the hero is standing still.</description>
		</command>
		<command id="puthero">
			<cannon>put hero (who,x,y)</cannon>
			<shortname>put hero</shortname>
			<description>Moves a hero to a precise location on the map. The first argument is the her&apos;s position in the walkabout party. The second and third arguments are the X,Y pixel position relative to the top left corner of the map. Be aware that using this command can mis-align your hero with the tile-grid, preventing it from walking normally. To position the hero by tile, use the <ref>setheroposition</ref> command.</description>
		</command>
	</section>
	<section title="Moving NPCs">
		<command id="npcreference">
			<cannon>NPC reference (ID,copy)</cannon>
			<shortname>NPC reference</shortname>
			<description>What is an NPC reference? A reference is a number that uniquely identifies an NPC on a map. You can use an NPC reference to specify which NPC you are controlling in most NPC-related commands. The first argument to NPC reference is the ID number of the NPC you want to work with. The ID is the same number that appears in CUSTOM.EXE when you are editing NPCs or placing NPCs on the map. The second argument is optional. It specifies which copy of the NPC you want, in case there are more than one on the map. If you dont specify which copy you want, you will just get a reference to the first NPC on the map with the right ID. If you plan on using the same NPC reference many times in a script you can store it in a <ref>variable</ref>. If the NPC with the ID you asked for (or the NPC copy you asked for with ID you asked for) is not found on the map then NPC reference will return <ref>false</ref>.</description>
			<example>include,plotscr.hsd
define script(1,ref example,none)

#---NPC reference example---

script,ref example,begin

  variable(Fred)

  # find the first copy of NPC 10,
  # and store the reference in a variable
  set variable(Fred,NPC reference(10,0))

  # now we can manipulate that NPC with the variable
  walk NPC     (Fred,south,3)
  wait for NPC (Fred)

  # make the NPC spin!
  set NPC direction (Fred,east)
  wait(2)
  set NPC direction (Fred,north)
  wait(2)
  set NPC direction (Fred,west)
  wait(2)
  set NPC direction (Fred,south)
  wait(2)

end</example>
			<seealso>
				<ref>npcatspot</ref>
				<ref>npcatpixel</ref>
				<ref>createnpc</ref>
			</seealso>
		</command>
		<command id="npcatspot">
			<cannon>NPC at spot (x,y,number)</cannon>
			<shortname>NPC at spot</shortname>
			<description>This command returns a reference to the NPC at the given X and Y coordinate on the map. The optional third argument lets you choose which NPC to reference in case there is more than one NPC standing on that same spot (starting from the bottom most NPC, which is number 0). You can also pass the constant <ref>getcount</ref> for the third argument to return the total number of npcs on that tile. Note that an NPC's tile is the tile its top left corner is on.</description>
			<seealso>
				<ref>npcreference</ref>
			</seealso>
		</command>
		<command id="npcatpixel">
			<cannon>NPC at pixel (x,y,number)</cannon>
			<shortname>NPC at pixel</shortname>